### ISSUE TITLE
Issues with the building pipeline

### ISSUE THREAD

**Issue by jlarrinzar** [sitmun/sitmun-admin-app-prototype#66] opened 2018-09-20 15:37 UTC
Adjunto pantallazo del fallo en el proceso de contruccion: 
![buildfail](https://user-images.githubusercontent.com/5917451/45829547-79bc5900-bcfb-11e8-9baf-ca70be3c42a2.png)

@montsemarco Según ha solicitado @fjlopez , ¿podrías ejecutar la construcción desde terminal con “gradlew clean assemble —stacktrace” para saber exactamente el error? (nos dará una traza de fallo) y también que me enviarais una captura del contenido de la carpeta “build”. Ah, y versión de Windows y que tipo de permisos tenéis en el equipo.

**Comment by montsemarco** [comment] 2018-09-21 09:45
The Operating System is Windows 2008 R2 Standard, the user has admin privileges (but is not the admin user). I made the tests with sitmun-territorial-app, the behavior is the same for both applications.

I attach the result of executing **gradlew clean assemble —stacktrace** from the console. 

[LOG_gradlew_clean_assemble-stacktrace_sitmun-terrritorial-app.txt](https://github.com/sitmun/sitmun-admin-app/files/2404773/LOG_gradlew_clean_assemble-stacktrace_sitmun-terrritorial-app.txt)

As you can see, the problem appears when Gradle tries to assemble the sitmun-plugin-core. The error message says that cannot find the npm.cmd (line 120).  

I think that the problem could be that the file is located in **sitmun-territorial-app\\.gradle\npm\npm-v6.2.0**  while Gradle tries to find it in **sitmun-territorial-app\build\plugins-src\sitmun-plugin-core .** . There is also a directory called **sitmun-territorial-app\build\plugins-src\sitmun-plugin-core\\.gradle\npm\npm-v6.2.0** but there is nothing on it

I attach the content of sitmun-territorial-app\build directory, as you requested 
[dirBuild.txt](https://github.com/sitmun/sitmun-admin-app/files/2404867/dirBuild.txt)

Just to say that, when cloning **sitmun-plugin-core** and executing the same command **gradlew clean assemble —stacktrace**, that is, doing the same job that is done by the sitmun-territorial-app, it finish successfully, In this case, I think that Gradle is searching npm.cmd in **sitmun-plugin-core\\.gradle\npm\npm-v6.2.0** properly.

**Comment by fjlopez** [comment] 2018-09-24 08:09
I have been able to reproduce the issue in **macOS**. It seems that the gradle plugin that manages node builds has a bug. A temporal fix is in progress.

**Comment by montsemarco** [comment] 2018-10-01 10:05
I followed the instructions from the wiki, that is, I installed **Node.js** on the computer to try to solve temporarily the problem.

Now the assemble task finishes properly, however, the **bootRun** task fails due to the **clonePlugins** task (I attach the screen with the entire message) .
![bootrunfails](https://user-images.githubusercontent.com/1905272/46282675-69fe0980-c572-11e8-8510-b23326ce2c5c.png)

I also attach the result when using the parameter --stacktrace

[bootRun_fails_with_stacktrace_param.txt](https://github.com/sitmun/sitmun-admin-app/files/2433658/bootRun_fails_with_stacktrace_param.txt)

**Comment by fjlopez** [comment] 2018-10-01 10:55
Root cause identified. Fix in progress.

**Comment by fjlopez** [comment] 2018-10-01 18:30
Pushed fixes to https://github.com/sitmun/sitmun-admin-app/commit/5eceee887b0268528c21aa144fc3af19efa315f5 and https://github.com/sitmun/sitmun-territorial-app/commit/ce68fa85c2255e85bca64ac03bcc9ba292bf00b9

@montsemarco now `gradlew.bat bootRun` after `gradlew.bat assemble` should work fine in both apps.

**Comment by montsemarco** [comment] 2018-10-02 10:54
Tested and working

**Closed as completed by montsemarco** 2018-10-02 10:54 UTC
Labels: bug
